// Bundles the inbox (src/inbox) into src/inbox/generated.ts, which both the
// Node server and the Cloudflare Worker import. Runs before build and test.
import { build } from 'tsup';
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

const here = path.dirname(new URL(import.meta.url).pathname);
const src = path.join(here, '..', 'src', 'inbox');
const out = mkdtempSync(path.join(tmpdir(), 'grabby-inbox-'));

try {
  await build({
    entry: { inbox: path.join(src, 'inbox.ts') },
    outDir: out,
    format: ['iife'],
    platform: 'browser',
    target: 'es2020',
    minify: true,
    noExternal: [/.*/],
    silent: true,
    config: false,
  });
  const js = readFileSync(path.join(out, 'inbox.global.js'), 'utf8');
  const css = readFileSync(path.join(src, 'inbox.css'), 'utf8');
  const html = readFileSync(path.join(src, 'index.html'), 'utf8');
  const hash = createHash('sha256').update(js).update(css).digest('hex').slice(0, 10);
  writeFileSync(path.join(src, 'generated.ts'), [
    '// Generated by scripts/build-inbox.mjs. Do not edit.',
    `export const INBOX = ${JSON.stringify({ html, js, css, hash })};`,
    '',
  ].join('\n'));
  console.log(`inbox: ${(js.length / 1024).toFixed(1)} KB js, ${(css.length / 1024).toFixed(1)} KB css (${hash})`);
} finally {
  rmSync(out, { recursive: true, force: true });
}
